name: 'reactive_web_core'
version: 0.0.1
description: >
  A starter template for a polymer.dart web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  stream_transformers: any
  vacuum_persistent: any
